name: CITYBUILDER3000 CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-client:
    name: Test Client
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'

    - name: Install client dependencies
      run: npm ci

    - name: Run client tests
      run: npm test --if-present

    - name: Run client linter
      run: npm run lint --if-present

    - name: Build client
      run: npm run build --if-present

  test-server:
    name: Test Server
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'

    - name: Install server dependencies
      run: npm ci

    - name: Run server tests
      run: npm test --if-present

    - name: Run server linter
      run: npm run lint --if-present

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: [test-client, test-server]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Audit client dependencies
      run: npm audit --prefix ./client

    - name: Audit server dependencies
      run: npm audit --prefix ./server

    - name: Audit root dependencies
      run: npm audit --if-present

  install-all:
    name: Install All Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install all dependencies (root, client, server)
      run: npm run install:all